/***********************************
 *  Name:           TrayIcon.h
 *  Description:    Creates an Icon in the tray that can manage the state of the application without GUI open
 *  Author(s):      Xander Palermo <ajp2s@missouristate.edu>
 *  Date:           April 2026
 *
 * Course:          CSC450
 ***********************************/

#ifndef PALETTE_TRAYICON_H
#define PALETTE_TRAYICON_H

#pragma once
#include <functional>
#include <iostream>
#include <ostream>
#include <windows.h>
#include <shellapi.h>
#include <string>

class TrayIcon {
public:
    std::function<void()> onLeftClick;
    std::function<void()> onExit;

private:
    static constexpr wchar_t APP_NAME[] = L"Palette";
    static constexpr UINT WM_TRAY = WM_APP + 1;
    static constexpr UINT ID_TRAY = 1001;

    // ID of context menu item
    static constexpr UINT IDM_OPEN = 2001;
    static constexpr UINT IDM_EXIT = 2002;


    HINSTANCE m_hInst;
    HWND m_hWnd;
    NOTIFYICONDATAW m_nid = {};

    /**
     *
     * @brief Event handler.
     *
     * Gives logic to the windows window to execute specific calls when an event is triggered
     *
     * Called by Windows itself; not by process
     *
     * @param hWnd Handle to the window
     * @param msg The message generated by the window
     * @param wParam Additional information about message
     * @param lParam Additional information about message
     * @returns 0 on OKAY STATUS during message handling
     * @returns Default WndProc result if message is not handled
     */
    static LRESULT CALLBACK WndProc(const HWND hWnd, const UINT msg, const WPARAM wParam, const LPARAM lParam) {
        if (msg == WM_CREATE) {
            auto* self = reinterpret_cast<CREATESTRUCT*>(lParam);
            SetWindowLongPtr(hWnd, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(self->lpCreateParams));
        }
        auto* self = reinterpret_cast<TrayIcon*>(GetWindowLongPtr(hWnd, GWLP_USERDATA));
        if (!self) return DefWindowProc(hWnd, msg, wParam, lParam);

        switch (msg) {
            case WM_TRAY:                                               // Process click on Tray Icon
                if (lParam == WM_LBUTTONDOWN && self->onLeftClick) {
                    self->onLeftClick();
                }
                if (lParam == WM_RBUTTONUP) {
                    self->showContextMenu();
                }
                return 0;
            case WM_COMMAND:                                            // Process click on Context Menu
                switch (LOWORD(wParam)) {
                    case IDM_OPEN:
                        //TODO: Open GUI Application
                        std::cout << "Application Open Request" << std::endl;
                        break;
                    case IDM_EXIT:
                        if (self->onExit) self->onExit();
                        DestroyWindow(hWnd);
                        break;
                }
                return 0;
            case WM_DESTROY:                                            // Process Destruction of Icon
                PostQuitMessage(0);
                return 0;
        }
        return DefWindowProc(hWnd, msg, wParam, lParam);
    }


    /**
     * @brief Registers a window template to Windows OS
     */
    void registerWindow() const;

    /**
     * @brief Uses window template registered to class to attempt to create a new window
     *
     * @pre window template has already been registered
     *
     * @returns 0 on success
     * @returns -1 on failure to create window
     */
    int createWindow();

    /**
     * @brief Adds Tray Icon to task bar for application
     *
     * @pre window associated with this process has been created
     */
    void addIcon();

    /**
     * @brief Establishes the structure of the right click menu
     *
     * @pre window associated with this process has been created
     */
    void showContextMenu() const;

    /**
     * @brief Listens for windows sent from Windows API and requests action upon them
     *
     * @pre window associated with this process has been created
     */
    static void processMessage();

    /**
     * @brief Calls Windows API to delete tray icon
     */
    void removeIcon();

    /**
     * @brief Calls Windows API to delete window for process
     */
    void destroyWindow() ;

public:
    explicit TrayIcon(HINSTANCE hInst) : m_hInst(hInst), m_hWnd(nullptr), m_nid{} {}

    ~TrayIcon();

    /**
     * @brief Creates Tray Icon and listens for events
     *
     * Does not return until Tray Icon is terminated
     */
    void run();
};


#endif //PALETTE_TRAYICON_H